services:
  app:
    build:
      context: ./php
    env_file:
      - .env.local # Chargement des variables Symfony
      - compose.env
    container_name: univet_app
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: compose.env
    container_name: univet_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: univet_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
